# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotquiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='picture',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
